[[snippets]]
  description = "Disable font smoothing on Mac"
  command = "defaults -currentHost write -g AppleFontSmoothing -int 0"
  output = ""

[[snippets]]
  description = "Drain nodes that are having issues"
  command = "kubectl drain --delete-local-data --ignore-daemonsets $NODE_IP && kubectl uncordon $NODE_IP"
  output = ""

[[snippets]]
  description = "Docker login staging"
  command = "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <AWSACCOUNT>.dkr.ecr.us-west-2.amazonaws.com"
  output = ""

[[snippets]]
  description = "Docker login dev"
  command = "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <AWSACCOUNT>.dkr.ecr.us-west-2.amazonaws.com"
  output = ""

[[snippets]]
  description = "Docker login prod"
  command = "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <AWSACCOUNT>.dkr.ecr.us-west-2.amazonaws.com"
  output = ""

[[snippets]]
  description = "jq - aws security groups"
  command = "cat ec2_instances.json | jq '.Reservations | .[] | .Instances | .[] | {InstanceId: .InstanceId,PrivateIp: .PrivateIpAddress,PublicIp: .PublicIpAddress,VpcId: .VpcId,PrivatedDnsName: .PrivateDnsName,PublicDnsName: .PublicDnsName,SecurityGroups: .SecurityGroups,Tags: [.Tags[]? | select(.Key == \"Name\")]}'"
  output = ""

[[snippets]]
  description = "jq - get security group rules"
  command = "cat sec_groups.json | jq '.SecurityGroups[] | {GroupName: .GroupName,VpcId: .VpcId,Description: .Description,IpPermissions: .IpPermissions}'"
  output = ""

[[snippets]]
  description = "Find fingerprint of public keys from authorized key file"
  command = "while read -r keys; do ssh-keygen -l -E md5 -f /dev/stdin;done <  <(cat keys)"
  output = ""

[[snippets]]
  description = "Get RDS connect token"
  command = "aws rds generate-db-auth-token --hostname {db or cluster endpoint} --port 3306 --username {db username}"
  output = ""

[[snippets]]
  description = "MySQL Dev port forward"
  command = "echo 'Tunneling' && ssh -N -L 3306:<BASTION>:3306 <DBHOST>"
  output = ""

[[snippets]]
  description = "Generate password"
  command = "date +%s | shasum | base64 | head -c 32 ; echo"
  output = ""
